# TODO: travis is outdated, the go test no longer has docker based test
# TODO: replace docker-compose w/ qaq16
language: go
sudo: true
services:
  - docker
go:
  - "1.14"
  - tip
git:
  depth: 3
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - docker version
  - docker-compose version
  - go get -u golang.org/x/tools/cmd/goimports
script:
  - (cd impl/rcl-go && make test && make install)
  # FIXME: java test is disabled due to file permission issue when bind volume https://github.com/reikalang/rcl/issues/6
  # - (cd impl/rcl-j && make docker-test)