language: go
sudo: true
services:
  - docker
git:
  depth: 3
install:
  - go get -u github.com/golang/dep/cmd/dep
  - docker version
  - docker-compose version
script:
  - (cd impl/rcl-go && make dep-install && make docker-test)
  - (cd impl/rcl-j && make docker-test)