version: "3.4"
services:
  # FIXME: it's just copy and paste ....
  # TODO: need to remove build and .gradle folder
  j8:
    image: "gradle:jdk8"
    working_dir: "/home/reika/rcl"
    command: "gradle --no-daemon test"
    volumes:
      - type: bind # TODO: bind or volume
        source: "."
        target: "/home/reika/rcl"
  j9:
    image: "gradle:jdk9"
    working_dir: "/home/reika/rcl"
    command: "gradle --no-daemon test"
    volumes:
      - type: bind # TODO: bind or volume
        source: "."
        target: "/home/reika/rcl"